FROM mariadb:11

# Ensure init scripts are baked into the image
COPY scripts/mariadb-init/ /docker-entrypoint-initdb.d/

# Set MariaDB port - https://mariadb.com/docs/server/server-management/install-and-upgrade-mariadb/configuring-mariadb/configuring-mariadb-with-option-files
# Use on env variable in sed - https://stackoverflow.com/questions/584894/environment-variable-substitution-in-sed#:~:text=You%20may%20need%20double%20quotes
ARG MARIADB_PORT=3306
RUN sed -i "/\[client-server\]/a port=${MARIADB_PORT}" /etc/mysql/mariadb.cnf